#!/bin/bash
#Xtightvnc -geometry 853x480 -rfbauth vncpass :13 &
cp files/xstartup ~/.vnc/xstartup
echo "exec $(pwd)/scrcap/dwm-6.0/dwm" >> ~/.vnc/xstartup
chmod 0700 ~/.vnc/xstartup
vncserver :13 -geometry 853x480 -alwaysshared
