#!/bin/bash
# -N : disable cursor pseudo encoding
OUTPUTFILE=$1
INSTALLDIR=$(dirname $(readlink -f "$0"))

. "$INSTALLDIR/.env/bin/activate"
PWDFILE="$INSTALLDIR/files/pwdfile"
flvrec.py -o $OUTPUTFILE -P "$PWDFILE" localhost:13 2>&1 >/dev/null &
#-P ~/.vnc/passwd localhost:13 -N
