#!/bin/bash
# -N : disable cursor pseudo encoding
. .env/bin/activate
set -u
OUTPUTFILE=$1
PWDFILE="$(pwd)/files/pwdfile"
flvrec.py -o $OUTPUTFILE -P "$PWDFILE" localhost:13 2>&1 >/dev/null &
#-P ~/.vnc/passwd localhost:13 -N
